extends Node
## Autoload "Sfx": sound effects and ambience.
##
## Sounds live in res://assets/sfx/ ("k:" = Kenney CC0 packs in kenney/, "s:" = procedurally synthesized in
## synth/, regenerated by assets/sfx/tools/gen_sfx.py). Positional one-shots use a pool of AudioStreamPlayer3D;
## the ambience is three quiet 2D loops (day / dusk / night) crossfaded by set_time_of_day().
## In --headless nothing is played, but `heard` still fires so the host's monsters can hunt by sound.

## Emitted on this peer for every positional sound (also headless), so AI can react: range_m is how far it carries.
signal heard(sound: String, pos: Vector3, range_m: float)

const KENNEY_DIR := "res://assets/sfx/kenney/"
const SYNTH_DIR := "res://assets/sfx/synth/"
const MAX_VOICES := 40
const AMBIENCE_DB := -14.0  ## loudness of a fully faded-in ambience loop
const AMBIENCE_FADE := 0.25  ## how fast the ambience weights follow the time of day, per second
const CREEP_DB := -6.0  ## extra attenuation of the random night one-shots

## name -> [variants, range in metres, volume dB, random pitch +-]. A random variant is picked each time.
const SOUNDS := {
	"footstep": [["k:footstep_grass_000", "k:footstep_grass_001", "k:footstep_grass_002",
			"k:footstep_grass_003", "k:footstep_grass_004"], 18.0, -8.0, 0.08],
	"jump_land": [["k:impactSoft_heavy_000", "k:impactSoft_heavy_001"], 20.0, -4.0, 0.08],
	"pickup": [["k:handleSmallLeather", "k:handleSmallLeather2"], 10.0, -6.0, 0.08],
	"drop": [["k:dropLeather"], 15.0, -3.0, 0.08],
	"throw": [["s:throw"], 15.0, -4.0, 0.08],
	"eat": [["s:eat"], 12.0, -2.0, 0.08],
	"vomit": [["s:vomit"], 30.0, 0.0, 0.06],
	"cash": [["k:handleCoins", "k:handleCoins2"], 12.0, -4.0, 0.08],
	"buy": [["k:confirmation_001"], 12.0, -6.0, 0.0],
	"slot_spin": [["s:slot_spin"], 20.0, -6.0, 0.0],
	"slot_win": [["s:slot_win"], 40.0, -3.0, 0.0],
	"slot_lose": [["s:slot_lose"], 30.0, -3.0, 0.0],
	"car_start": [["s:car_start"], 50.0, 0.0, 0.0],
	"car_engine": [["s:car_engine"], 45.0, -2.0, 0.0],
	"car_horn": [["s:car_horn"], 90.0, 0.0, 0.0],
	"car_crash": [["s:car_crash", "k:impactMetal_heavy_000"], 80.0, 0.0, 0.05],
	"door": [["k:doorOpen_1", "k:doorOpen_2"], 25.0, -3.0, 0.08],
	"door_close": [["k:doorClose_1"], 25.0, -3.0, 0.08],
	"flashlight_click": [["k:switch_001"], 8.0, -6.0, 0.05],
	"battery": [["k:metalClick"], 8.0, -4.0, 0.05],
	"whistle": [["s:whistle"], 80.0, 0.0, 0.04],
	"flare": [["s:flare"], 30.0, -4.0, 0.05],
	"flare_loop": [["s:flare_loop"], 25.0, -8.0, 0.0],
	"scream": [["s:scream"], 60.0, 0.0, 0.08],
	"hag_laugh": [["s:hag_laugh"], 50.0, 0.0, 0.05],
	"hag_scream": [["s:hag_scream"], 90.0, 2.0, 0.05],
	"hag_whisper": [["s:hag_whisper"], 12.0, -2.0, 0.05],
	"hag_breath": [["s:hag_breath"], 15.0, -4.0, 0.0],
	"wolf_howl": [["s:wolf_howl"], 160.0, 0.0, 0.07],
	"wolf_growl": [["s:wolf_growl"], 30.0, 0.0, 0.08],
	"police_siren": [["s:police_siren"], 150.0, -2.0, 0.0],
	"walkie_on": [["s:walkie_on"], 10.0, -6.0, 0.0],
	"walkie_off": [["s:walkie_off"], 10.0, -6.0, 0.0],
	"heartbeat": [["s:heartbeat"], 6.0, -2.0, 0.0],
	"pa_chime": [["s:pa_chime"], 120.0, -2.0, 0.0],
	"organ": [["s:organ"], 70.0, -2.0, 0.0],
	"cave_in": [["s:cave_in"], 120.0, 2.0, 0.05],
	"gurney": [["s:gurney"], 25.0, -6.0, 0.05],
	"tray_drop": [["k:impactPlate_heavy_000", "k:impactPlate_heavy_001"], 35.0, -2.0, 0.08],
	"mushroom_break": [["s:mushroom_break"], 12.0, -4.0, 0.08],
	"witch_cackle": [["s:witch_cackle"], 45.0, 0.0, 0.05],
	"splash": [["s:splash"], 25.0, -2.0, 0.08],
	"ui_click": [["k:click_001"], 0.0, -8.0, 0.04],
	"owl_hoot": [["s:owl_hoot"], 70.0, -6.0, 0.04],
	"branch_snap": [["s:branch_snap"], 30.0, -2.0, 0.08],
	"explosion": [["k:lowFrequency_explosion_000"], 120.0, 0.0, 0.05],
	"rock_hit": [["k:impactMining_000"], 25.0, -3.0, 0.08],
	"metal_hit": [["k:impactMetal_heavy_000"], 35.0, -3.0, 0.08],
}
const AMBIENCE := ["s:amb_day", "s:amb_dusk", "s:amb_night"]
## Random night one-shots around the listener: [sound, min distance, max distance].
const CREEPS := [["wolf_howl", 60.0, 110.0], ["owl_hoot", 20.0, 45.0], ["owl_hoot", 25.0, 50.0],
		["branch_snap", 9.0, 18.0]]

var _audio := DisplayServer.get_name() != "headless"
var _streams := {}  ## sound name -> Array[AudioStream]
var _warned := {}
var _free_3d: Array[AudioStreamPlayer3D] = []
var _free_2d: Array[AudioStreamPlayer] = []
var _active := 0
var _amb: Array[AudioStreamPlayer] = []
var _amb_target := [0.0, 0.0, 0.0]
var _amb_weight := [0.0, 0.0, 0.0]
var _creep_timer := 20.0


func _ready() -> void:
	set_process(false)


## This peer only: play a one-shot sound at a position (Vector3.INF = not positional).
func play(sound: String, pos := Vector3.INF, volume_db := 0.0) -> void:
	_play(sound, pos, volume_db, true)


## Any peer: play a sound for everyone (relayed through the host when online).
func play_all(sound: String, pos := Vector3.INF, volume_db := 0.0) -> void:
	var peer := multiplayer.multiplayer_peer
	if peer == null or peer is OfflineMultiplayerPeer \
			or peer.get_connection_status() != MultiplayerPeer.CONNECTION_CONNECTED:
		play(sound, pos, volume_db)
		return
	_play_rpc.rpc(sound, pos, volume_db)


## Every peer, by the level: 0 = morning ... 0.5 = dusk ... 1 = midnight; crossfades the ambience.
func set_time_of_day(t: float) -> void:
	t = clampf(t, 0.0, 1.0)
	_amb_target = [maxf(0.0, 1.0 - t * 2.0), 1.0 - absf(t - 0.5) * 2.0, maxf(0.0, t * 2.0 - 1.0)]
	if not _audio:
		return
	if _amb.is_empty():
		for key: String in AMBIENCE:
			var p := AudioStreamPlayer.new()
			p.stream = _looped(_load(key))
			p.volume_db = -80.0
			p.autoplay = true
			add_child(p)
			_amb.append(p)
		_amb_weight = _amb_target.duplicate()  # first call: jump straight there, no fade from silence
	set_process(true)


## Silences the ambience (e.g. back in the menu).
func stop_ambience() -> void:
	for p in _amb:
		p.queue_free()
	_amb.clear()
	_amb_weight = [0.0, 0.0, 0.0]
	set_process(false)


## Attaches a looping positional sound to `parent` (car engine, hag breathing, siren...) and starts it.
## The caller owns the returned player: change pitch_scale / volume_db, stop() or queue_free() it.
func loop(sound: String, parent: Node3D) -> AudioStreamPlayer3D:
	var p := AudioStreamPlayer3D.new()
	p.name = "Loop_" + sound
	var def: Array = SOUNDS.get(sound, [])
	if def.is_empty():
		_warn(sound)
	else:
		_setup_3d(p, def[1], def[2])
		p.stream = _looped(_pick(sound))
	p.autoplay = _audio and p.stream != null  # starts as soon as it is in the tree
	parent.add_child(p)
	return p


# ---------------------------------------------------------------- internals

@rpc("any_peer", "call_local", "reliable")
func _play_rpc(sound: String, pos: Vector3, volume_db: float) -> void:
	play(sound, pos, volume_db)


func _play(sound: String, pos: Vector3, volume_db: float, emit: bool) -> void:
	var def: Array = SOUNDS.get(sound, [])
	if def.is_empty():
		_warn(sound)
		return
	var positional := pos.is_finite()
	if emit and positional:
		heard.emit(sound, pos, def[1])
	if not _audio or _active >= MAX_VOICES or not is_inside_tree():
		return
	var stream := _pick(sound)
	if stream == null:
		return
	var pitch := 1.0 + randf_range(-def[3], def[3])
	if positional:
		var p3: AudioStreamPlayer3D = _free_3d.pop_back() if not _free_3d.is_empty() else _new_3d()
		_setup_3d(p3, def[1], def[2] + volume_db)
		p3.position = pos
		p3.stream = stream
		p3.pitch_scale = pitch
		p3.play()
	else:
		var p2: AudioStreamPlayer = _free_2d.pop_back() if not _free_2d.is_empty() else _new_2d()
		p2.volume_db = def[2] + volume_db
		p2.stream = stream
		p2.pitch_scale = pitch
		p2.play()
	_active += 1


func _new_3d() -> AudioStreamPlayer3D:
	var p := AudioStreamPlayer3D.new()
	add_child(p)
	p.finished.connect(func() -> void:
		_active -= 1
		_free_3d.append(p))
	return p


func _new_2d() -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	add_child(p)
	p.finished.connect(func() -> void:
		_active -= 1
		_free_2d.append(p))
	return p


## Inverse-distance falloff: full volume within range/5, about -14 dB at range, silent past it.
func _setup_3d(p: AudioStreamPlayer3D, range_m: float, volume_db: float) -> void:
	range_m = maxf(range_m, 4.0)
	p.attenuation_model = AudioStreamPlayer3D.ATTENUATION_INVERSE_DISTANCE
	p.unit_size = range_m / 5.0
	p.max_distance = range_m
	p.volume_db = volume_db
	p.attenuation_filter_cutoff_hz = 6000.0


func _pick(sound: String) -> AudioStream:
	if not _streams.has(sound):
		var list: Array[AudioStream] = []
		for key: String in SOUNDS[sound][0]:
			var s := _load(key)
			if s != null:
				list.append(s)
		_streams[sound] = list
	var variants: Array[AudioStream] = _streams[sound]
	return null if variants.is_empty() else variants.pick_random()


## "k:name" -> kenney/name.ogg, "s:name" -> synth/name.ogg (or .wav when regenerated without ffmpeg).
func _load(key: String) -> AudioStream:
	var dir := KENNEY_DIR if key.begins_with("k:") else SYNTH_DIR
	var base := dir + key.substr(2)
	for ext in [".ogg", ".wav"]:
		if ResourceLoader.exists(base + ext):
			return load(base + ext) as AudioStream
	push_warning("Sfx: missing file " + base)
	return null


## A looping copy of the stream (the shared one-shot resource is left alone).
func _looped(stream: AudioStream) -> AudioStream:
	if stream == null:
		return null
	var s: AudioStream = stream.duplicate()
	if s is AudioStreamOggVorbis:
		(s as AudioStreamOggVorbis).loop = true
	elif s is AudioStreamWAV:
		var w := s as AudioStreamWAV
		w.loop_mode = AudioStreamWAV.LOOP_FORWARD
		w.loop_begin = 0
		w.loop_end = int(w.get_length() * w.mix_rate)
	return s


func _warn(sound: String) -> void:
	if not _warned.has(sound):
		_warned[sound] = true
		push_warning("Sfx: unknown sound '%s'" % sound)


func _process(delta: float) -> void:
	for i in _amb.size():
		_amb_weight[i] = move_toward(_amb_weight[i], _amb_target[i], AMBIENCE_FADE * delta)
		var w: float = _amb_weight[i]
		_amb[i].volume_db = AMBIENCE_DB + linear_to_db(w) if w > 0.001 else -80.0
	_creep_timer -= delta
	if _creep_timer <= 0.0:
		_creep_timer = randf_range(12.0, 35.0)
		if randf() < _amb_weight[2]:
			_creep()


## A distant howl / owl / snapping branch somewhere around the listener. Not sent to `heard`.
func _creep() -> void:
	var cam := get_viewport().get_camera_3d()
	if cam == null:
		return
	var c: Array = CREEPS.pick_random()
	var dir := Vector3.FORWARD.rotated(Vector3.UP, randf() * TAU)
	var pos := cam.global_position + dir * randf_range(c[1], c[2]) + Vector3.UP * randf_range(0.0, 3.0)
	_play(c[0], pos, CREEP_DB, false)
